server:
  port: 18081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

#配置seata注册中心
    alibaba:
      seata:
        tx-service-group: gmall_tx_group


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379

  zipkin:

    base-url: http://localhost:9411

    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto


feign:
  sentinel:
    enabled: true
logging:
  level:
    root: info
