server:
  port: 18085

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        dashboard: localhost:8080


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  redis:
    host: localhost:6379

  zipkin:
    base-url: http:localhost:9411
    sender:
      type: web
    discovery-client-enabled: false



  sleuth:
    sampler:
      probability: 1


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #映射的实体类
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto

feign:
  sentinel:
    enabled: true
